language: php
matrix:
  include:
    - php: 5.3
      env: AUTOLOAD=1
      dist: precise
    - php: 5.3
      env: AUTOLOAD=0
      dist: precise
    - php: 5.4
      env: AUTOLOAD=1
    - php: 5.4
      env: AUTOLOAD=0
    - php: 5.5
      env: AUTOLOAD=1
    - php: 5.5
      env: AUTOLOAD=0
    - php: 5.6
      env: AUTOLOAD=1
    - php: 5.6
      env: AUTOLOAD=0
    - php: 7.0
      env: AUTOLOAD=1
    - php: 7.0
      env: AUTOLOAD=0
    - php: 7.1
      env: AUTOLOAD=1
    - php: 7.1
      env: AUTOLOAD=0
    - php: 7.2
      env: AUTOLOAD=1
    - php: 7.2
      env: AUTOLOAD=0
    - php: hhvm
      env: AUTOLOAD=1
    - php: hhvm
      env: AUTOLOAD=0
